version: "3.7"

services:
  pythoncli:
    image: gpudeep:latest
    runtime:nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /data:/data
    container_name: "gpu-deeplearn"